---
fontsize: 10pt
latex-before-packages-includes:
    - \PassOptionsToPackage{labelfont=bf,labelsep=period,justification=raggedright}{caption}
    - \topmargin 0.0cm
    - \oddsidemargin 0.5cm
    - \evensidemargin 0.5cm
    - \textwidth 16cm
    - \textheight 21cm
latex-after-packages-includes:
    - \usepackage{pdflscape}
    - \makeatletter\renewcommand{\@biblabel}[1]{\quad#1.}\makeatother
latex-header-includes:
    - \date{}
    - \pagestyle{myheadings}
    - \newcommand{\initiateLandscape}{\begin{landscape}}
    - \newcommand{\terminateLandscape}{\end{landscape}}
    - \DeclareUnicodeCharacter{00A0}{ }
natbib-options:
    - super
    - comma
csl: scholdoc.csl
css: scholmd.css

# This commands have to be added manually for Nature-style citations:
# \usepackage[super,comma]{natbib}
# \bibpunct{}{}{,}{s}{}{\textsuperscript{,}}
# \renewcommand\bibnumfmt[1]{#1.}
# \bibliographystyle{naturemag}

# Also add \pagebreak after the last main Figure

...

